name: tictactoe
description: A sample mobile game built in Flutter.

# Prevent accidental publishing to pub.dev.
publish_to: 'none'

version: 1.7.9+36

environment:
  sdk: ">=2.17.0-0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  audioplayers: ^5.1.0
  cupertino_icons: ^1.0.2
  go_router: ^13.1.0
  logging: ^1.1.0
  provider: ^6.0.2
  shared_preferences: ^2.0.13

  firebase_core: ^2.1.1  # Needed for Crashlytics below
  firebase_crashlytics: ^3.0.3  # Error reporting
  games_services: ^4.0.0  # Achievements and leaderboards
  google_mobile_ads: ^4.0.0  # Ads
  in_app_purchase: ^3.0.1  # In-app purchases
  in_app_purchase_android: ^0.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1
  test: ^1.19.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/music/
    - assets/sfx/

  fonts:
    - family: Permanent Marker
      fonts:
        - asset: assets/Permanent_Marker/PermanentMarker-Regular.ttf

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/icon-adaptive-foreground.png"
