// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDQIkqXSs-UgR50LJzjkfs8IDQc_Go8j4w',
    appId: '1:896194001523:android:76b4ed240c98ad30df8806',
    messagingSenderId: '896194001523',
    projectId: 'tic-tac-toe-flutter-game',
    storageBucket: 'tic-tac-toe-flutter-game.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCD9PK5PP4biD5dvnG54VS43Kij2nnKmAk',
    appId: '1:896194001523:ios:63053024fbfcddbcdf8806',
    messagingSenderId: '896194001523',
    projectId: 'tic-tac-toe-flutter-game',
    storageBucket: 'tic-tac-toe-flutter-game.appspot.com',
    iosClientId: '896194001523-147dv4s44ieqlavbbso6p00fqk0p952f.apps.googleusercontent.com',
    iosBundleId: 'dev.flutter.tictactoe',
  );
}
